# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distractor', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'documents/')),
                ('status', models.SmallIntegerField(choices=[(0, b'In Queue'), (1, b'Processing'), (2, b'Complete'), (-1, b'Error')], default=0)),
                ('title', models.CharField(default=b'', max_length=64)),
                ('created_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnText', models.CharField(max_length=256)),
                ('ans', models.CharField(max_length=64)),
                ('qnNo', models.IntegerField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='revup_common.Document')),
            ],
            options={
                'ordering': ['qnNo'],
            },
        ),
        migrations.CreateModel(
            name='RevupUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='distractor',
            name='qn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distractors', to='revup_common.Question'),
        ),
    ]
